FROM python:3.9-slim-bullseye AS build

WORKDIR /container

COPY . /container

RUN echo "Installing dependencies..." \
    && ls -la \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r dependencias.txt