services:
  envio-email:
    container_name: container
    image: emails_diarios:latest
    build:
      context: ../
      dockerfile: ./.containeremail/Dockerfile
    env_file:
      - ../.configs/.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/container:z
    command: sleep infinity

    # docker compose -f .containeremail/docker-compose.yml down --rmi all --volumes
    # docker compose -f .containeremail/docker-compose.yml up --build -d
    